# Generated by Django 5.1 on 2026-02-08 00:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Source",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120, unique=True)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("homepage", models.URLField(blank=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="Feed",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=160)),
                ("url", models.URLField(unique=True)),
                (
                    "feed_type",
                    models.CharField(
                        choices=[("rss", "RSS"), ("atom", "Atom"), ("json", "JSON")],
                        default="rss",
                        max_length=20,
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("advisories", "Advisories"),
                            ("research", "Research"),
                            ("sweden", "Sweden"),
                        ],
                        default="advisories",
                        max_length=20,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("timeout_seconds", models.PositiveSmallIntegerField(default=10)),
                ("max_bytes", models.PositiveIntegerField(default=1500000)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="feeds", to="intel.source"),
                ),
            ],
            options={"ordering": ["source__name", "name"]},
        ),
        migrations.CreateModel(
            name="FetchRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("started_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("ok", models.BooleanField(default=False)),
                ("error", models.TextField(blank=True)),
                ("http_status", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("items_new", models.PositiveIntegerField(default=0)),
                ("items_updated", models.PositiveIntegerField(default=0)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "feed",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="fetch_runs", to="intel.feed"),
                ),
            ],
            options={"ordering": ["-started_at"]},
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=500)),
                ("normalized_title", models.CharField(blank=True, max_length=500)),
                ("title_hash", models.CharField(db_index=True, max_length=64)),
                ("url", models.URLField(blank=True, max_length=1500)),
                ("canonical_url", models.URLField(blank=True, db_index=True, max_length=1500)),
                ("stable_id", models.CharField(max_length=64, unique=True)),
                ("published_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("summary", models.TextField(blank=True)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "feed",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="intel.feed"),
                ),
                (
                    "source",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="intel.source"),
                ),
            ],
            options={"ordering": ["-published_at", "-id"]},
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(fields=["-published_at"], name="intel_item_pub_idx"),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(fields=["source", "-published_at"], name="intel_item_src_pub_idx"),
        ),
    ]
