# Generated by Django 5.2.11 on 2026-02-19 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel', '0002_feed_max_age_days_feed_max_items_per_run_and_msrc_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='normalized_title',
            field=models.CharField(blank=True, max_length=1500),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=1500),
        ),
    ]
