# Generated by Django 5.2.11 on 2026-02-28 00:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intel", "0003_alter_item_normalized_title_alter_item_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="DarkSource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120, unique=True)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("homepage", models.URLField(blank=True)),
                ("url", models.URLField(max_length=1500)),
                ("enabled", models.BooleanField(default=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("watch_keywords", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DarkFetchRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("started_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("ok", models.BooleanField(default=False)),
                ("error", models.TextField(blank=True)),
                ("bytes_received", models.PositiveIntegerField(default=0)),
                (
                    "dark_source",
                    models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="fetch_runs", to="intel.darksource"),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="DarkHit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("detected_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("matched_keywords", models.JSONField(blank=True, default=list)),
                ("title", models.CharField(max_length=500)),
                ("excerpt", models.TextField(blank=True)),
                ("url", models.TextField()),
                ("content_hash", models.CharField(max_length=64)),
                ("raw", models.TextField(blank=True)),
                (
                    "dark_source",
                    models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="hits", to="intel.darksource"),
                ),
            ],
            options={
                "ordering": ["-detected_at", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="darkhit",
            constraint=models.UniqueConstraint(
                fields=("dark_source", "content_hash"),
                name="intel_darkhit_source_hash_uniq",
            ),
        ),
    ]
