# Generated by Django 5.1.1 on 2026-03-07 12:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel', '0004_dark_intel_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='DarkDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1500)),
                ('canonical_url', models.URLField(blank=True, db_index=True, max_length=1500)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('excerpt', models.TextField(blank=True)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('last_http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-last_seen', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DarkSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetched_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('excerpt', models.TextField(blank=True)),
                ('raw', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-fetched_at', '-id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='darkhit',
            name='intel_darkhit_source_hash_uniq',
        ),
        migrations.AddField(
            model_name='darkfetchrun',
            name='documents_discovered',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='darkfetchrun',
            name='documents_fetched',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='darkfetchrun',
            name='duration_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='darkfetchrun',
            name='final_url',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='darkfetchrun',
            name='hits_new',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='darkfetchrun',
            name='hits_updated',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='darkfetchrun',
            name='http_status',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='darkhit',
            name='last_seen_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='darkhit',
            name='matched_regex',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='darksource',
            name='source_type',
            field=models.CharField(choices=[('single_page', 'Single Page'), ('index_page', 'Index Page'), ('feed', 'RSS/Atom Feed')], default='single_page', max_length=20),
        ),
        migrations.AddField(
            model_name='darksource',
            name='use_tor',
            field=models.BooleanField(default=False, help_text='Force Tor even for clearnet sources. Onion URLs always use Tor.'),
        ),
        migrations.AddField(
            model_name='darksource',
            name='watch_regex',
            field=models.TextField(blank=True, help_text='One regex per line.'),
        ),
        migrations.AddField(
            model_name='feed',
            name='adapter_key',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='feed',
            name='expanded_collection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feed',
            name='expanded_max_age_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feed',
            name='expanded_max_items_per_run',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feed',
            name='priority',
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='fetchrun',
            name='items_deduped',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fetchrun',
            name='items_fetched',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fetchrun',
            name='items_limited',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fetchrun',
            name='items_skipped_invalid',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fetchrun',
            name='items_skipped_old',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fetchrun',
            name='items_stored',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='darkdocument',
            name='dark_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='intel.darksource'),
        ),
        migrations.AddField(
            model_name='darkhit',
            name='dark_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hits', to='intel.darkdocument'),
        ),
        migrations.AddConstraint(
            model_name='darkhit',
            constraint=models.UniqueConstraint(fields=('dark_document', 'content_hash'), name='intel_darkhit_doc_hash_uniq'),
        ),
        migrations.AddField(
            model_name='darksnapshot',
            name='dark_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='intel.darkdocument'),
        ),
        migrations.AddConstraint(
            model_name='darkdocument',
            constraint=models.UniqueConstraint(fields=('dark_source', 'canonical_url'), name='intel_darkdoc_source_canonical_uniq'),
        ),
        migrations.AddConstraint(
            model_name='darkdocument',
            constraint=models.UniqueConstraint(fields=('dark_source', 'url'), name='intel_darkdoc_source_url_uniq'),
        ),
    ]
