# Generated by Django 5.1.1 on 2026-03-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel', '0006_opsjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='darksource',
            name='fetch_retries',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Optional per-source retry count override.', null=True),
        ),
        migrations.AddField(
            model_name='darksource',
            name='max_bytes',
            field=models.PositiveIntegerField(blank=True, help_text='Optional per-source response size cap in bytes.', null=True),
        ),
        migrations.AddField(
            model_name='darksource',
            name='timeout_seconds',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Optional per-source timeout override (seconds).', null=True),
        ),
    ]
