# Generated by Django 5.1.1 on 2026-03-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intel", "0007_darksource_fetch_retries_darksource_max_bytes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="darksource",
            name="extractor_profile",
            field=models.CharField(
                choices=[
                    ("generic_page", "Generic Page"),
                    ("incident_cards", "Incident Cards"),
                    ("group_cards", "Group Cards"),
                    ("table_rows", "Table Rows"),
                ],
                default="generic_page",
                help_text="How fetched pages should be turned into matchable records.",
                max_length=20,
            ),
        ),
    ]
