# Generated by Django 5.1.1 on 2026-03-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intel", "0008_darksource_extractor_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="darkhit",
            name="country",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="darkhit",
            name="group_name",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name="darkhit",
            name="industry",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="darkhit",
            name="last_activity_text",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="darkhit",
            name="record_type",
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AddField(
            model_name="darkhit",
            name="victim_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="darkhit",
            name="victim_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="darkhit",
            name="website_url",
            field=models.URLField(blank=True, max_length=1500),
        ),
    ]
