# Generated by Django 5.2.11 on 2026-08-28 05:50

from django.db import migrations, models


def preserve_existing_immediate_policy(apps, schema_editor):
    Feed = apps.get_model("intel", "Feed")
    Feed.objects.exclude(adapter_key="ransomware_live_victims").update(
        discord_enabled=True,
        discord_min_priority="P3",
        discord_mode="immediate",
    )
    Feed.objects.filter(adapter_key="ransomware_live_victims").update(
        discord_enabled=True,
        discord_min_priority="P3",
        discord_mode="digest",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('intel', '0011_darkhit_alert_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='discord_enabled',
            field=models.BooleanField(default=False, help_text='Allow this feed to participate in Discord notification policy.'),
        ),
        migrations.AddField(
            model_name='feed',
            name='discord_min_priority',
            field=models.CharField(choices=[('P1', 'P1 - Critical'), ('P2', 'P2 - High'), ('P3', 'P3 - Medium'), ('P4', 'P4 - Low / informational')], default='P3', help_text='Lowest-priority item eligible for Discord delivery.', max_length=2),
        ),
        migrations.AddField(
            model_name='feed',
            name='discord_mode',
            field=models.CharField(choices=[('immediate', 'Immediate'), ('digest', 'Digest (reserved)'), ('off', 'Off')], default='off', help_text='Digest is reserved for later and suppresses immediate delivery.', max_length=16),
        ),
        migrations.RunPython(
            preserve_existing_immediate_policy,
            migrations.RunPython.noop,
        ),
    ]
