version: "3.8"

services:
  db:
    image: docker.io/library/postgres:16
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: Containerfile
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DJANGO_SETTINGS_MODULE: config.settings.prod
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: unless-stopped

volumes:
  pgdata:
