version: "3.8"

services:
  db:
    image: docker.io/library/postgres:16
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  tor:
    image: docker.io/dperson/torproxy:latest
    restart: unless-stopped
    # Ingen ports: Tor ska bara vara åtkomlig internt i compose-nätet
    # Default lyssnar den på 9050 internt.

  web:
    build:
      context: .
      dockerfile: Containerfile
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DJANGO_SETTINGS_MODULE: config.settings.prod
      # Viktigt: använd service-namnet "tor" här
      DARK_TOR_SOCKS_URL: socks5h://tor:9050
      GUNICORN_CMD_ARGS: "--access-logfile - --error-logfile - --capture-output --log-level info"
    ports:
      - "8000:8000"
    depends_on:
      - db
      - tor
    restart: unless-stopped

volumes:
  pgdata: