DISABLED_FEED_URLS = {
    "https://www.debian.org/security/dsa.en.rdf",
    "https://access.redhat.com/security/data/metrics/recently-published-cve.rss",
    "https://security.access.redhat.com/data/metrics/recently-published-cve.rss",
}

TIER1_SOURCES = [
    {
        "name": "CERT-SE",
        "slug": "cert-se",
        "homepage": "https://www.cert.se/",
        "tags": ["government", "sweden"],
        "enabled": True,
        "feeds": [
            {
                "name": "CERT-SE Feed",
                "url": "https://www.cert.se/feed/",
                "feed_type": "rss",
                "adapter_key": "",
                "section": "sweden",
                "enabled": True,
                "timeout_seconds": 10,
                "max_bytes": 1_500_000,
                "max_age_days": 180,
                "max_items_per_run": 200,
            }
        ],
    },
    {
        "name": "CISA",
        "slug": "cisa",
        "homepage": "https://www.cisa.gov/",
        "tags": ["government", "us"],
        "enabled": True,
        "feeds": [
            {
                "name": "CISA Alerts",
                "url": "https://www.cisa.gov/uscert/ncas/alerts.xml",
                "feed_type": "rss",
                "adapter_key": "",
                "section": "active",
                "enabled": True,
                "timeout_seconds": 10,
                "max_bytes": 1_500_000,
                "max_age_days": 180,
                "max_items_per_run": 200,
            },
            {
                "name": "CISA KEV Catalog (JSON)",
                "url": "https://www.cisa.gov/sites/default/files/feeds/known_exploited_vulnerabilities.json",
                "feed_type": "json",
                "adapter_key": "cisa_kev",
                "section": "active",
                "enabled": True,
                "timeout_seconds": 15,
                "max_bytes": 2_500_000,
                "max_age_days": 3650,
                "max_items_per_run": 5000,
                "expanded_max_items_per_run": 10000,
                "expanded_max_age_days": 3650,
            },
        ],
    },
    {
        "name": "MSRC",
        "slug": "msrc",
        "homepage": "https://msrc.microsoft.com/",
        "tags": ["vendor", "microsoft"],
        "enabled": True,
        "feeds": [
            {
                "name": "MSRC Security Updates",
                "url": "https://api.msrc.microsoft.com/update-guide/rss",
                "feed_type": "rss",
                "adapter_key": "",
                "section": "advisories",
                "enabled": True,
                "timeout_seconds": 10,
                "max_bytes": 1_500_000,
                "max_age_days": 90,
                "max_items_per_run": 200,
            }
        ],
    },
    {
        "name": "Cisco",
        "slug": "cisco",
        "homepage": "https://sec.cloudapps.cisco.com/security/center/publicationListing.x",
        "tags": ["vendor", "network"],
        "enabled": True,
        "feeds": [
            {
                "name": "Cisco Security Advisories",
                "url": "https://sec.cloudapps.cisco.com/security/center/psirtrss20/CiscoSecurityAdvisory.xml",
                "feed_type": "rss",
                "adapter_key": "",
                "section": "advisories",
                "enabled": True,
                "timeout_seconds": 10,
                "max_bytes": 1_500_000,
                "max_age_days": 180,
                "max_items_per_run": 200,
            }
        ],
    },
    {
        "name": "Red Hat",
        "slug": "red-hat",
        "homepage": "https://access.redhat.com/security",
        "tags": ["vendor", "linux"],
        "enabled": True,
        "feeds": [
            {
                "name": "Red Hat RHSA Feed",
                "url": "https://access.redhat.com/security/data/metrics/recently-released-rhsa.rss",
                "feed_type": "rss",
                "adapter_key": "",
                "section": "advisories",
                "enabled": True,
                "timeout_seconds": 10,
                "max_bytes": 1_500_000,
                "max_age_days": 180,
                "max_items_per_run": 200,
            }
        ],
    },
    {
        "name": "Debian",
        "slug": "debian",
        "homepage": "https://www.debian.org/security/",
        "tags": ["vendor", "linux"],
        "enabled": True,
        "feeds": [
            {
                "name": "Debian DSA Feed",
                "url": "https://www.debian.org/security/dsa.rdf",
                "feed_type": "rss",
                "adapter_key": "",
                "section": "advisories",
                "enabled": True,
                "timeout_seconds": 10,
                "max_bytes": 1_500_000,
                "max_age_days": 180,
                "max_items_per_run": 200,
            }
        ],
    },
    {
        "name": "SANS ISC",
        "slug": "sans-isc",
        "homepage": "https://isc.sans.edu/",
        "tags": ["research"],
        "enabled": True,
        "feeds": [
            {
                "name": "SANS ISC Diaries",
                "url": "https://isc.sans.edu/rssfeed.xml",
                "feed_type": "rss",
                "adapter_key": "",
                "section": "research",
                "enabled": True,
                "timeout_seconds": 10,
                "max_bytes": 1_500_000,
                "max_age_days": 180,
                "max_items_per_run": 200,
            }
        ],
    },
    {
        "name": "ZDI",
        "slug": "zdi",
        "homepage": "https://www.zerodayinitiative.com/",
        "tags": ["research", "threat-intel"],
        "enabled": True,
        "feeds": [
            {
                "name": "ZDI Blog",
                "url": "https://www.zerodayinitiative.com/blog?format=rss",
                "feed_type": "rss",
                "adapter_key": "",
                "section": "research",
                "enabled": True,
                "timeout_seconds": 10,
                "max_bytes": 1_500_000,
                "max_age_days": 180,
                "max_items_per_run": 200,
            }
        ],
    },
    {
        "name": "Ransomware.live Victims",
        "slug": "ransomware-live",
        "homepage": "https://www.ransomware.live",
        "tags": ["ransomware", "threat-intel", "victims", "priority"],
        "enabled": True,
        "feeds": [
            {
                "name": "Ransomware.live Recent Victims",
                "url": "https://api.ransomware.live/v2/recentvictims",
                "feed_type": "json",
                "adapter_key": "ransomware_live_victims",
                "section": "active",
                "enabled": True,
                "timeout_seconds": 15,
                "max_bytes": 2_000_000,
                "max_age_days": 7,
                "max_items_per_run": 200,
            }
        ],
    },
    {
        "name": "Bleeping Computer",
        "slug": "bleeping-computer",
        "homepage": "https://www.bleepingcomputer.com",
        "tags": ["news", "ransomware", "incident"],
        "enabled": True,
        "feeds": [
            {
                "name": "Bleeping Computer Feed",
                "url": "https://www.bleepingcomputer.com/feed/",
                "feed_type": "rss",
                "adapter_key": "",
                "section": "active",
                "enabled": True,
                "timeout_seconds": 10,
                "max_bytes": 1_500_000,
                "max_age_days": 14,
                "max_items_per_run": 50,
            }
        ],
    },
    {
        "name": "Fortinet PSIRT",
        "slug": "fortinet",
        "homepage": "https://www.fortiguard.com/psirt",
        "tags": ["vendor", "network", "firewall"],
        "enabled": True,
        "feeds": [
            {
                "name": "Fortinet PSIRT Feed",
                "url": "https://filestore.fortinet.com/fortiguard/rss/ir.xml",
                "feed_type": "rss",
                "adapter_key": "",
                "section": "advisories",
                "enabled": True,
                "timeout_seconds": 10,
                "max_bytes": 1_500_000,
                "max_age_days": 180,
                "max_items_per_run": 100,
            }
        ],
    },
    {
        "name": "Palo Alto Networks PSIRT",
        "slug": "palo-alto",
        "homepage": "https://security.paloaltonetworks.com",
        "tags": ["vendor", "network", "firewall"],
        "enabled": True,
        "feeds": [
            {
                "name": "Palo Alto Networks PSIRT Feed",
                "url": "https://security.paloaltonetworks.com/rss.xml",
                "feed_type": "rss",
                "adapter_key": "",
                "section": "advisories",
                "enabled": True,
                "timeout_seconds": 10,
                "max_bytes": 1_500_000,
                "max_age_days": 180,
                "max_items_per_run": 100,
            }
        ],
    },
    {
        "name": "FIRST.org EPSS",
        "slug": "epss",
        "homepage": "https://www.first.org/epss",
        "tags": ["threat-intel", "cve", "scoring"],
        "enabled": True,
        "feeds": [
            {
                "name": "EPSS Top CVEs (7 days)",
                "url": "https://api.first.org/data/v1/epss?days=7&limit=200&order=!epss",
                "feed_type": "json",
                "adapter_key": "epss",
                "section": "active",
                "enabled": True,
                "timeout_seconds": 15,
                "max_bytes": 2_000_000,
                "max_age_days": 14,
                "max_items_per_run": 200,
            }
        ],
    },
    {
        "name": "Exploit-DB",
        "slug": "exploit-db",
        "homepage": "https://www.exploit-db.com",
        "tags": ["research", "offensive", "poc"],
        "enabled": True,
        "feeds": [
            {
                "name": "Exploit-DB Feed",
                "url": "https://www.exploit-db.com/rss.xml",
                "feed_type": "rss",
                "adapter_key": "",
                "section": "research",
                "enabled": True,
                "timeout_seconds": 10,
                "max_bytes": 1_500_000,
                "max_age_days": 90,
                "max_items_per_run": 100,
            }
        ],
    },
]
